# Generated by Django 4.1.6 on 2023-02-09 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_news', models.CharField(max_length=500)),
                ('time_news', models.DateTimeField(auto_now_add=True)),
                ('correspondent_fname', models.CharField(max_length=255)),
                ('category_news', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
