# Generated by Django 4.1.6 on 2023-02-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_about_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title_news',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
