# Generated by Django 4.1.6 on 2023-02-09 14:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_about_city_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_city',
            name='url_channel',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='category_news',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', 'Культура'), ('', 'Интернет'), ('', 'Наука и технологии'), ('', 'Некрологи'), ('', 'Общество'), ('', 'Политика'), ('', 'Преступность и право'), ('', 'Проишествия'), ('', 'Рейтинги'), ('', 'Религия'), ('', 'Дни рождения'), ('', 'Спорт'), ('', 'Экономика')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='correspondent_fname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
